Built mobile header and headline
ONJoseph/Portfolio pull request #1
Opened 2022-02-17 18:40 UTC by ONJoseph

Project setup

2022-02-17 20:08 UTC, nicupop729 reviewed
# INVALID Code Review Request :stop_sign: 

Hi @ONJoseph , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that fails the linter checks.
And please add `.gitignore` file with `node_modules/` folder in it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

2022-02-17 23:49 UTC, ONJoseph commented on README.md
> -# Portfolio
edit

2022-02-18 01:09 UTC, codepantherr requested changes
Hi @ONJoseph 👋, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media1.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## To Highlight: ⚡ 
- Descriptive Readme
- Meaningful PR

## Suggested changes
- [ ] Please remove all unused CSS code. Most of the code you have there are not required at this stage of the project.

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-18 01:09 UTC, codepantherr commented on index.html
> +            <h3 class="work-title">My Recent Works</h3>
- [ ] Even though you have done an amazing job, this section down to the footer is outside the scope of this project for now. Kindly remove ❌  them as they are not required at this stage of the project.

2022-02-18 20:18 UTC, closed without merging